// This file was generated by WTL Dialog wizard 
// UrlInputDlg.cpp : Implementation of CUrlInputDlg

#include "stdafx.h"
#include "UrlInputDlg.h"

// CUrlInputDlg
CUrlInputDlg::CUrlInputDlg()
{
}

CUrlInputDlg::~CUrlInputDlg()
{
}

LRESULT CUrlInputDlg::OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	DoDataExchange();
	return 1;  // Let the system set the focus
}

LRESULT CUrlInputDlg::OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
{
	DoDataExchange(TRUE);
	EndDialog(wID);
	return 0;
}

LRESULT CUrlInputDlg::OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
{
	EndDialog(wID);
	return 0;
}

bool CUrlInputDlg::Execute(CString& sUrl)
{
	CUrlInputDlg dlg;
	dlg.m_strUrlEdit = sUrl;
	int nResult = dlg.DoModal();
	sUrl = dlg.m_strUrlEdit;
	return nResult == IDOK;
}
