// This file was generated by WTL Dialog wizard 
// UrlInputDlg.h : Declaration of the CUrlInputDlg

#pragma once

#include "resource.h"       // main symbols
#include <atlddx.h>
// CUrlInputDlg

class CUrlInputDlg : 
	public CDialogImpl<CUrlInputDlg>,
	public CWinDataExchange<CUrlInputDlg>	
{
	CString m_strUrlEdit;
public:
	CUrlInputDlg();
	~CUrlInputDlg();
	enum { IDD = IDD_DIALOG1 };
	static bool Execute(CString& sUrl);
    BEGIN_MSG_MAP(CUrlInputDlg)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
    END_MSG_MAP()

	BEGIN_DDX_MAP(CUrlInputDlg)
		DDX_TEXT(IDC_URL_EDIT, m_strUrlEdit)
	END_DDX_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
};


